/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTimelineRouteImport } from './routes/_authenticated/timeline'
import { Route as AuthenticatedTargetsRouteImport } from './routes/_authenticated/targets'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedPendingRouteImport } from './routes/_authenticated/pending'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedNextActionsRouteImport } from './routes/_authenticated/next-actions'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedJourneyRouteImport } from './routes/_authenticated/journey'
import { Route as AuthenticatedEvidencesRouteImport } from './routes/_authenticated/evidences'
import { Route as AuthenticatedDownloadsRouteImport } from './routes/_authenticated/downloads'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComparativeRouteImport } from './routes/_authenticated/comparative'
import { Route as AuthenticatedCollectionRouteImport } from './routes/_authenticated/collection'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedChangeRequestsRouteImport } from './routes/_authenticated/change-requests'
import { Route as AuthenticatedAskAiRouteImport } from './routes/_authenticated/ask-ai'
import { Route as AuthenticatedMissionsIndexRouteImport } from './routes/_authenticated/missions.index'
import { Route as AuthenticatedMissionsNewRouteImport } from './routes/_authenticated/missions.new'
import { Route as AuthenticatedMissionsMissionIdRouteImport } from './routes/_authenticated/missions.$missionId'
import { Route as AuthenticatedMissionsMissionIdIndexRouteImport } from './routes/_authenticated/missions.$missionId.index'
import { Route as AuthenticatedMissionsMissionIdTargetsRouteImport } from './routes/_authenticated/missions.$missionId.targets'
import { Route as AuthenticatedMissionsMissionIdJourneyRouteImport } from './routes/_authenticated/missions.$missionId.journey'
import { Route as AuthenticatedMissionsMissionIdDocumentRouteImport } from './routes/_authenticated/missions.$missionId.document'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimelineRoute = AuthenticatedTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTargetsRoute = AuthenticatedTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendingRoute = AuthenticatedPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNextActionsRoute =
  AuthenticatedNextActionsRouteImport.update({
    id: '/next-actions',
    path: '/next-actions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJourneyRoute = AuthenticatedJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvidencesRoute = AuthenticatedEvidencesRouteImport.update({
  id: '/evidences',
  path: '/evidences',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDownloadsRoute = AuthenticatedDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComparativeRoute =
  AuthenticatedComparativeRouteImport.update({
    id: '/comparative',
    path: '/comparative',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollectionRoute = AuthenticatedCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangeRequestsRoute =
  AuthenticatedChangeRequestsRouteImport.update({
    id: '/change-requests',
    path: '/change-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAskAiRoute = AuthenticatedAskAiRouteImport.update({
  id: '/ask-ai',
  path: '/ask-ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMissionsIndexRoute =
  AuthenticatedMissionsIndexRouteImport.update({
    id: '/missions/',
    path: '/missions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMissionsNewRoute =
  AuthenticatedMissionsNewRouteImport.update({
    id: '/missions/new',
    path: '/missions/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMissionsMissionIdRoute =
  AuthenticatedMissionsMissionIdRouteImport.update({
    id: '/missions/$missionId',
    path: '/missions/$missionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMissionsMissionIdIndexRoute =
  AuthenticatedMissionsMissionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdTargetsRoute =
  AuthenticatedMissionsMissionIdTargetsRouteImport.update({
    id: '/targets',
    path: '/targets',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdJourneyRoute =
  AuthenticatedMissionsMissionIdJourneyRouteImport.update({
    id: '/journey',
    path: '/journey',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdDocumentRoute =
  AuthenticatedMissionsMissionIdDocumentRouteImport.update({
    id: '/document',
    path: '/document',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ask-ai': typeof AuthenticatedAskAiRoute
  '/change-requests': typeof AuthenticatedChangeRequestsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/collection': typeof AuthenticatedCollectionRoute
  '/comparative': typeof AuthenticatedComparativeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/downloads': typeof AuthenticatedDownloadsRoute
  '/evidences': typeof AuthenticatedEvidencesRoute
  '/journey': typeof AuthenticatedJourneyRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/next-actions': typeof AuthenticatedNextActionsRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/products': typeof AuthenticatedProductsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/targets': typeof AuthenticatedTargetsRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/users': typeof AuthenticatedUsersRoute
  '/missions/$missionId': typeof AuthenticatedMissionsMissionIdRouteWithChildren
  '/missions/new': typeof AuthenticatedMissionsNewRoute
  '/missions/': typeof AuthenticatedMissionsIndexRoute
  '/missions/$missionId/document': typeof AuthenticatedMissionsMissionIdDocumentRoute
  '/missions/$missionId/journey': typeof AuthenticatedMissionsMissionIdJourneyRoute
  '/missions/$missionId/targets': typeof AuthenticatedMissionsMissionIdTargetsRoute
  '/missions/$missionId/': typeof AuthenticatedMissionsMissionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ask-ai': typeof AuthenticatedAskAiRoute
  '/change-requests': typeof AuthenticatedChangeRequestsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/collection': typeof AuthenticatedCollectionRoute
  '/comparative': typeof AuthenticatedComparativeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/downloads': typeof AuthenticatedDownloadsRoute
  '/evidences': typeof AuthenticatedEvidencesRoute
  '/journey': typeof AuthenticatedJourneyRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/next-actions': typeof AuthenticatedNextActionsRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/products': typeof AuthenticatedProductsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/targets': typeof AuthenticatedTargetsRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/users': typeof AuthenticatedUsersRoute
  '/missions/new': typeof AuthenticatedMissionsNewRoute
  '/missions': typeof AuthenticatedMissionsIndexRoute
  '/missions/$missionId/document': typeof AuthenticatedMissionsMissionIdDocumentRoute
  '/missions/$missionId/journey': typeof AuthenticatedMissionsMissionIdJourneyRoute
  '/missions/$missionId/targets': typeof AuthenticatedMissionsMissionIdTargetsRoute
  '/missions/$missionId': typeof AuthenticatedMissionsMissionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/ask-ai': typeof AuthenticatedAskAiRoute
  '/_authenticated/change-requests': typeof AuthenticatedChangeRequestsRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/collection': typeof AuthenticatedCollectionRoute
  '/_authenticated/comparative': typeof AuthenticatedComparativeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/downloads': typeof AuthenticatedDownloadsRoute
  '/_authenticated/evidences': typeof AuthenticatedEvidencesRoute
  '/_authenticated/journey': typeof AuthenticatedJourneyRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/next-actions': typeof AuthenticatedNextActionsRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/pending': typeof AuthenticatedPendingRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/targets': typeof AuthenticatedTargetsRoute
  '/_authenticated/timeline': typeof AuthenticatedTimelineRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/missions/$missionId': typeof AuthenticatedMissionsMissionIdRouteWithChildren
  '/_authenticated/missions/new': typeof AuthenticatedMissionsNewRoute
  '/_authenticated/missions/': typeof AuthenticatedMissionsIndexRoute
  '/_authenticated/missions/$missionId/document': typeof AuthenticatedMissionsMissionIdDocumentRoute
  '/_authenticated/missions/$missionId/journey': typeof AuthenticatedMissionsMissionIdJourneyRoute
  '/_authenticated/missions/$missionId/targets': typeof AuthenticatedMissionsMissionIdTargetsRoute
  '/_authenticated/missions/$missionId/': typeof AuthenticatedMissionsMissionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ask-ai'
    | '/change-requests'
    | '/clients'
    | '/collection'
    | '/comparative'
    | '/dashboard'
    | '/documents'
    | '/downloads'
    | '/evidences'
    | '/journey'
    | '/logs'
    | '/next-actions'
    | '/notificacoes'
    | '/pending'
    | '/products'
    | '/reports'
    | '/settings'
    | '/targets'
    | '/timeline'
    | '/users'
    | '/missions/$missionId'
    | '/missions/new'
    | '/missions/'
    | '/missions/$missionId/document'
    | '/missions/$missionId/journey'
    | '/missions/$missionId/targets'
    | '/missions/$missionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ask-ai'
    | '/change-requests'
    | '/clients'
    | '/collection'
    | '/comparative'
    | '/dashboard'
    | '/documents'
    | '/downloads'
    | '/evidences'
    | '/journey'
    | '/logs'
    | '/next-actions'
    | '/notificacoes'
    | '/pending'
    | '/products'
    | '/reports'
    | '/settings'
    | '/targets'
    | '/timeline'
    | '/users'
    | '/missions/new'
    | '/missions'
    | '/missions/$missionId/document'
    | '/missions/$missionId/journey'
    | '/missions/$missionId/targets'
    | '/missions/$missionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/ask-ai'
    | '/_authenticated/change-requests'
    | '/_authenticated/clients'
    | '/_authenticated/collection'
    | '/_authenticated/comparative'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/downloads'
    | '/_authenticated/evidences'
    | '/_authenticated/journey'
    | '/_authenticated/logs'
    | '/_authenticated/next-actions'
    | '/_authenticated/notificacoes'
    | '/_authenticated/pending'
    | '/_authenticated/products'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/targets'
    | '/_authenticated/timeline'
    | '/_authenticated/users'
    | '/_authenticated/missions/$missionId'
    | '/_authenticated/missions/new'
    | '/_authenticated/missions/'
    | '/_authenticated/missions/$missionId/document'
    | '/_authenticated/missions/$missionId/journey'
    | '/_authenticated/missions/$missionId/targets'
    | '/_authenticated/missions/$missionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timeline': {
      id: '/_authenticated/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AuthenticatedTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/targets': {
      id: '/_authenticated/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof AuthenticatedTargetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pending': {
      id: '/_authenticated/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AuthenticatedPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/next-actions': {
      id: '/_authenticated/next-actions'
      path: '/next-actions'
      fullPath: '/next-actions'
      preLoaderRoute: typeof AuthenticatedNextActionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journey': {
      id: '/_authenticated/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof AuthenticatedJourneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evidences': {
      id: '/_authenticated/evidences'
      path: '/evidences'
      fullPath: '/evidences'
      preLoaderRoute: typeof AuthenticatedEvidencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/downloads': {
      id: '/_authenticated/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AuthenticatedDownloadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comparative': {
      id: '/_authenticated/comparative'
      path: '/comparative'
      fullPath: '/comparative'
      preLoaderRoute: typeof AuthenticatedComparativeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collection': {
      id: '/_authenticated/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof AuthenticatedCollectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-requests': {
      id: '/_authenticated/change-requests'
      path: '/change-requests'
      fullPath: '/change-requests'
      preLoaderRoute: typeof AuthenticatedChangeRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ask-ai': {
      id: '/_authenticated/ask-ai'
      path: '/ask-ai'
      fullPath: '/ask-ai'
      preLoaderRoute: typeof AuthenticatedAskAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missions/': {
      id: '/_authenticated/missions/'
      path: '/missions'
      fullPath: '/missions/'
      preLoaderRoute: typeof AuthenticatedMissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missions/new': {
      id: '/_authenticated/missions/new'
      path: '/missions/new'
      fullPath: '/missions/new'
      preLoaderRoute: typeof AuthenticatedMissionsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missions/$missionId': {
      id: '/_authenticated/missions/$missionId'
      path: '/missions/$missionId'
      fullPath: '/missions/$missionId'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missions/$missionId/': {
      id: '/_authenticated/missions/$missionId/'
      path: '/'
      fullPath: '/missions/$missionId/'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdIndexRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/targets': {
      id: '/_authenticated/missions/$missionId/targets'
      path: '/targets'
      fullPath: '/missions/$missionId/targets'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdTargetsRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/journey': {
      id: '/_authenticated/missions/$missionId/journey'
      path: '/journey'
      fullPath: '/missions/$missionId/journey'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdJourneyRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/document': {
      id: '/_authenticated/missions/$missionId/document'
      path: '/document'
      fullPath: '/missions/$missionId/document'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdDocumentRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
  }
}

interface AuthenticatedMissionsMissionIdRouteChildren {
  AuthenticatedMissionsMissionIdDocumentRoute: typeof AuthenticatedMissionsMissionIdDocumentRoute
  AuthenticatedMissionsMissionIdJourneyRoute: typeof AuthenticatedMissionsMissionIdJourneyRoute
  AuthenticatedMissionsMissionIdTargetsRoute: typeof AuthenticatedMissionsMissionIdTargetsRoute
  AuthenticatedMissionsMissionIdIndexRoute: typeof AuthenticatedMissionsMissionIdIndexRoute
}

const AuthenticatedMissionsMissionIdRouteChildren: AuthenticatedMissionsMissionIdRouteChildren =
  {
    AuthenticatedMissionsMissionIdDocumentRoute:
      AuthenticatedMissionsMissionIdDocumentRoute,
    AuthenticatedMissionsMissionIdJourneyRoute:
      AuthenticatedMissionsMissionIdJourneyRoute,
    AuthenticatedMissionsMissionIdTargetsRoute:
      AuthenticatedMissionsMissionIdTargetsRoute,
    AuthenticatedMissionsMissionIdIndexRoute:
      AuthenticatedMissionsMissionIdIndexRoute,
  }

const AuthenticatedMissionsMissionIdRouteWithChildren =
  AuthenticatedMissionsMissionIdRoute._addFileChildren(
    AuthenticatedMissionsMissionIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAskAiRoute: typeof AuthenticatedAskAiRoute
  AuthenticatedChangeRequestsRoute: typeof AuthenticatedChangeRequestsRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedCollectionRoute: typeof AuthenticatedCollectionRoute
  AuthenticatedComparativeRoute: typeof AuthenticatedComparativeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedDownloadsRoute: typeof AuthenticatedDownloadsRoute
  AuthenticatedEvidencesRoute: typeof AuthenticatedEvidencesRoute
  AuthenticatedJourneyRoute: typeof AuthenticatedJourneyRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedNextActionsRoute: typeof AuthenticatedNextActionsRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPendingRoute: typeof AuthenticatedPendingRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTargetsRoute: typeof AuthenticatedTargetsRoute
  AuthenticatedTimelineRoute: typeof AuthenticatedTimelineRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedMissionsMissionIdRoute: typeof AuthenticatedMissionsMissionIdRouteWithChildren
  AuthenticatedMissionsNewRoute: typeof AuthenticatedMissionsNewRoute
  AuthenticatedMissionsIndexRoute: typeof AuthenticatedMissionsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAskAiRoute: AuthenticatedAskAiRoute,
  AuthenticatedChangeRequestsRoute: AuthenticatedChangeRequestsRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedCollectionRoute: AuthenticatedCollectionRoute,
  AuthenticatedComparativeRoute: AuthenticatedComparativeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedDownloadsRoute: AuthenticatedDownloadsRoute,
  AuthenticatedEvidencesRoute: AuthenticatedEvidencesRoute,
  AuthenticatedJourneyRoute: AuthenticatedJourneyRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedNextActionsRoute: AuthenticatedNextActionsRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPendingRoute: AuthenticatedPendingRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTargetsRoute: AuthenticatedTargetsRoute,
  AuthenticatedTimelineRoute: AuthenticatedTimelineRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedMissionsMissionIdRoute:
    AuthenticatedMissionsMissionIdRouteWithChildren,
  AuthenticatedMissionsNewRoute: AuthenticatedMissionsNewRoute,
  AuthenticatedMissionsIndexRoute: AuthenticatedMissionsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
