/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTargetsRouteImport } from './routes/_authenticated/targets'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCollectionRouteImport } from './routes/_authenticated/collection'
import { Route as AuthenticatedMissionsIndexRouteImport } from './routes/_authenticated/missions.index'
import { Route as AuthenticatedMissionsNewRouteImport } from './routes/_authenticated/missions.new'
import { Route as AuthenticatedMissionsMissionIdRouteImport } from './routes/_authenticated/missions.$missionId'
import { Route as AuthenticatedMissionsMissionIdIndexRouteImport } from './routes/_authenticated/missions.$missionId.index'
import { Route as AuthenticatedMissionsMissionIdTargetsRouteImport } from './routes/_authenticated/missions.$missionId.targets'
import { Route as AuthenticatedMissionsMissionIdDocumentRouteImport } from './routes/_authenticated/missions.$missionId.document'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTargetsRoute = AuthenticatedTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectionRoute = AuthenticatedCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMissionsIndexRoute =
  AuthenticatedMissionsIndexRouteImport.update({
    id: '/missions/',
    path: '/missions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMissionsNewRoute =
  AuthenticatedMissionsNewRouteImport.update({
    id: '/missions/new',
    path: '/missions/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMissionsMissionIdRoute =
  AuthenticatedMissionsMissionIdRouteImport.update({
    id: '/missions/$missionId',
    path: '/missions/$missionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMissionsMissionIdIndexRoute =
  AuthenticatedMissionsMissionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdTargetsRoute =
  AuthenticatedMissionsMissionIdTargetsRouteImport.update({
    id: '/targets',
    path: '/targets',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdDocumentRoute =
  AuthenticatedMissionsMissionIdDocumentRouteImport.update({
    id: '/document',
    path: '/document',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collection': typeof AuthenticatedCollectionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/targets': typeof AuthenticatedTargetsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/missions/$missionId': typeof AuthenticatedMissionsMissionIdRouteWithChildren
  '/missions/new': typeof AuthenticatedMissionsNewRoute
  '/missions/': typeof AuthenticatedMissionsIndexRoute
  '/missions/$missionId/document': typeof AuthenticatedMissionsMissionIdDocumentRoute
  '/missions/$missionId/targets': typeof AuthenticatedMissionsMissionIdTargetsRoute
  '/missions/$missionId/': typeof AuthenticatedMissionsMissionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collection': typeof AuthenticatedCollectionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/targets': typeof AuthenticatedTargetsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/missions/new': typeof AuthenticatedMissionsNewRoute
  '/missions': typeof AuthenticatedMissionsIndexRoute
  '/missions/$missionId/document': typeof AuthenticatedMissionsMissionIdDocumentRoute
  '/missions/$missionId/targets': typeof AuthenticatedMissionsMissionIdTargetsRoute
  '/missions/$missionId': typeof AuthenticatedMissionsMissionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/collection': typeof AuthenticatedCollectionRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/targets': typeof AuthenticatedTargetsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/missions/$missionId': typeof AuthenticatedMissionsMissionIdRouteWithChildren
  '/_authenticated/missions/new': typeof AuthenticatedMissionsNewRoute
  '/_authenticated/missions/': typeof AuthenticatedMissionsIndexRoute
  '/_authenticated/missions/$missionId/document': typeof AuthenticatedMissionsMissionIdDocumentRoute
  '/_authenticated/missions/$missionId/targets': typeof AuthenticatedMissionsMissionIdTargetsRoute
  '/_authenticated/missions/$missionId/': typeof AuthenticatedMissionsMissionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/collection'
    | '/dashboard'
    | '/documents'
    | '/targets'
    | '/users'
    | '/missions/$missionId'
    | '/missions/new'
    | '/missions/'
    | '/missions/$missionId/document'
    | '/missions/$missionId/targets'
    | '/missions/$missionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/collection'
    | '/dashboard'
    | '/documents'
    | '/targets'
    | '/users'
    | '/missions/new'
    | '/missions'
    | '/missions/$missionId/document'
    | '/missions/$missionId/targets'
    | '/missions/$missionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/collection'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/targets'
    | '/_authenticated/users'
    | '/_authenticated/missions/$missionId'
    | '/_authenticated/missions/new'
    | '/_authenticated/missions/'
    | '/_authenticated/missions/$missionId/document'
    | '/_authenticated/missions/$missionId/targets'
    | '/_authenticated/missions/$missionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/targets': {
      id: '/_authenticated/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof AuthenticatedTargetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collection': {
      id: '/_authenticated/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof AuthenticatedCollectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missions/': {
      id: '/_authenticated/missions/'
      path: '/missions'
      fullPath: '/missions/'
      preLoaderRoute: typeof AuthenticatedMissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missions/new': {
      id: '/_authenticated/missions/new'
      path: '/missions/new'
      fullPath: '/missions/new'
      preLoaderRoute: typeof AuthenticatedMissionsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missions/$missionId': {
      id: '/_authenticated/missions/$missionId'
      path: '/missions/$missionId'
      fullPath: '/missions/$missionId'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missions/$missionId/': {
      id: '/_authenticated/missions/$missionId/'
      path: '/'
      fullPath: '/missions/$missionId/'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdIndexRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/targets': {
      id: '/_authenticated/missions/$missionId/targets'
      path: '/targets'
      fullPath: '/missions/$missionId/targets'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdTargetsRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/document': {
      id: '/_authenticated/missions/$missionId/document'
      path: '/document'
      fullPath: '/missions/$missionId/document'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdDocumentRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
  }
}

interface AuthenticatedMissionsMissionIdRouteChildren {
  AuthenticatedMissionsMissionIdDocumentRoute: typeof AuthenticatedMissionsMissionIdDocumentRoute
  AuthenticatedMissionsMissionIdTargetsRoute: typeof AuthenticatedMissionsMissionIdTargetsRoute
  AuthenticatedMissionsMissionIdIndexRoute: typeof AuthenticatedMissionsMissionIdIndexRoute
}

const AuthenticatedMissionsMissionIdRouteChildren: AuthenticatedMissionsMissionIdRouteChildren =
  {
    AuthenticatedMissionsMissionIdDocumentRoute:
      AuthenticatedMissionsMissionIdDocumentRoute,
    AuthenticatedMissionsMissionIdTargetsRoute:
      AuthenticatedMissionsMissionIdTargetsRoute,
    AuthenticatedMissionsMissionIdIndexRoute:
      AuthenticatedMissionsMissionIdIndexRoute,
  }

const AuthenticatedMissionsMissionIdRouteWithChildren =
  AuthenticatedMissionsMissionIdRoute._addFileChildren(
    AuthenticatedMissionsMissionIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCollectionRoute: typeof AuthenticatedCollectionRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedTargetsRoute: typeof AuthenticatedTargetsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedMissionsMissionIdRoute: typeof AuthenticatedMissionsMissionIdRouteWithChildren
  AuthenticatedMissionsNewRoute: typeof AuthenticatedMissionsNewRoute
  AuthenticatedMissionsIndexRoute: typeof AuthenticatedMissionsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCollectionRoute: AuthenticatedCollectionRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedTargetsRoute: AuthenticatedTargetsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedMissionsMissionIdRoute:
    AuthenticatedMissionsMissionIdRouteWithChildren,
  AuthenticatedMissionsNewRoute: AuthenticatedMissionsNewRoute,
  AuthenticatedMissionsIndexRoute: AuthenticatedMissionsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
